@userId=0e4c9286-0ba5-4205-b7f3-9261a6d85899
@postId=b722636b-c50c-4651-863c-078745230357

### 建立廢文資料(POST)
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "Hi I'm Taki!",
  "content": "I love Tomorin~",
  "userId": "0e4c9286-0ba5-4205-b7f3-9261a6d85899"
}

### 取得廢文列表順便抓出是誰發的廢文(GET)
GET http://localhost:3000/post/{{userId}}
Content-Type: application/json

### 編輯廢文(PATCH)
PATCH http://localhost:3000/post/{{postId}}
Content-Type: application/json

{
  "title": "Umirin Editing",
  "content": "TakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisukiTakisuki"
}

### 刪除廢文(DELETE)
DELETE http://localhost:3000/post/{{postId}}